#ifndef _NUMBER_INCLUDED_
#define _NUMBER_INCLUDED_

void num0()
      {
       PORTB.0 = 1;  //seg1-A1
       PORTB.1 = 1;
       PORTB.1 = 0;   
       PORTB.0 = 1;  //seg1-A2
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 1;  //seg1-B
       PORTB.1 = 1;
       PORTB.1 = 0;  
       PORTB.0 = 1;  //seg1-C
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 1;  //seg1-D2
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 1;  //seg1-D1
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 1;  //seg1-E
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 1;  //seg1-F
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 0;  //seg1-H
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 0;  //seg1-J
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 0;  //seg1-K
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 0;  //seg1-G2
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 0;  //seg1-L
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 0;  //seg1-M
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 0;  //seg1-N
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 0;  //seg1-G1
       PORTB.1 = 1;
       PORTB.1 = 0;
      }         
      
void num1()
      {
       PORTB.0 = 0;  //seg1-A1
       PORTB.1 = 1;
       PORTB.1 = 0;   
       PORTB.0 = 0;  //seg1-A2
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 1;  //seg1-B
       PORTB.1 = 1;
       PORTB.1 = 0;  
       PORTB.0 = 1;  //seg1-C
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 0;  //seg1-D2
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 0;  //seg1-D1
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 0;  //seg1-E
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 0;  //seg1-F
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 0;  //seg1-H
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 0;  //seg1-J
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 1;  //seg1-K
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 0;  //seg1-G2
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 0;  //seg1-L
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 0;  //seg1-M
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 0;  //seg1-N
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 0;  //seg1-G1
       PORTB.1 = 1;
       PORTB.1 = 0;
      }

void num2()
      {
       PORTB.0 = 1;  //seg1-A1
       PORTB.1 = 1;
       PORTB.1 = 0;   
       PORTB.0 = 1;  //seg1-A2
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 1;  //seg1-B
       PORTB.1 = 1;
       PORTB.1 = 0;  
       PORTB.0 = 0;  //seg1-C
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 1;  //seg1-D2
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 1;  //seg1-D1
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 1;  //seg1-E
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 0;  //seg1-F
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 0;  //seg1-H
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 0;  //seg1-J
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 0;  //seg1-K
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 1;  //seg1-G2
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 0;  //seg1-L
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 0;  //seg1-M
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 0;  //seg1-N
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 1;  //seg1-G1
       PORTB.1 = 1;
       PORTB.1 = 0;
      }  
      
           
void num3()
      {
       PORTB.0 = 1;  //seg1-A1
       PORTB.1 = 1;
       PORTB.1 = 0;   
       PORTB.0 = 1;  //seg1-A2
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 1;  //seg1-B
       PORTB.1 = 1;
       PORTB.1 = 0;  
       PORTB.0 = 1;  //seg1-C
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 1;  //seg1-D2
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 1;  //seg1-D1
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 0;  //seg1-E
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 0;  //seg1-F
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 0;  //seg1-H
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 0;  //seg1-J
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 0;  //seg1-K
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 1;  //seg1-G2
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 0;  //seg1-L
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 0;  //seg1-M
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 0;  //seg1-N
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 1;  //seg1-G1
       PORTB.1 = 1;
       PORTB.1 = 0;
      }
      
void num4()
      {
       PORTB.0 = 0;  //seg1-A1
       PORTB.1 = 1;
       PORTB.1 = 0;   
       PORTB.0 = 0;  //seg1-A2
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 1;  //seg1-B
       PORTB.1 = 1;
       PORTB.1 = 0;  
       PORTB.0 = 1;  //seg1-C
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 0;  //seg1-D2
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 0;  //seg1-D1
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 0;  //seg1-E
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 1;  //seg1-F
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 0;  //seg1-H
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 0;  //seg1-J
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 0;  //seg1-K
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 1;  //seg1-G2
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 0;  //seg1-L
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 0;  //seg1-M
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 0;  //seg1-N
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 1;  //seg1-G1
       PORTB.1 = 1;
       PORTB.1 = 0;
      }
      
void num5()
      {
       PORTB.0 = 1;  //seg1-A1
       PORTB.1 = 1;
       PORTB.1 = 0;   
       PORTB.0 = 1;  //seg1-A2
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 0;  //seg1-B
       PORTB.1 = 1;
       PORTB.1 = 0;  
       PORTB.0 = 1;  //seg1-C
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 1;  //seg1-D2
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 1;  //seg1-D1
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 0;  //seg1-E
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 1;  //seg1-F
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 0;  //seg1-H
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 0;  //seg1-J
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 0;  //seg1-K
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 1;  //seg1-G2
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 0;  //seg1-L
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 0;  //seg1-M
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 0;  //seg1-N
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 1;  //seg1-G1
       PORTB.1 = 1;
       PORTB.1 = 0;
      }
      
void num6()
      {
       PORTB.0 = 1;  //seg1-A1
       PORTB.1 = 1;
       PORTB.1 = 0;   
       PORTB.0 = 1;  //seg1-A2
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 0;  //seg1-B
       PORTB.1 = 1;
       PORTB.1 = 0;  
       PORTB.0 = 1;  //seg1-C
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 1;  //seg1-D2
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 1;  //seg1-D1
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 1;  //seg1-E
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 1;  //seg1-F
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 0;  //seg1-H
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 0;  //seg1-J
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 0;  //seg1-K
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 1;  //seg1-G2
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 0;  //seg1-L
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 0;  //seg1-M
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 0;  //seg1-N
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 1;  //seg1-G1
       PORTB.1 = 1;
       PORTB.1 = 0;
      }
      
void num7()
      {
       PORTB.0 = 1;  //seg1-A1
       PORTB.1 = 1;
       PORTB.1 = 0;   
       PORTB.0 = 1;  //seg1-A2
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 1;  //seg1-B
       PORTB.1 = 1;
       PORTB.1 = 0;  
       PORTB.0 = 1;  //seg1-C
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 0;  //seg1-D2
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 0;  //seg1-D1
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 0;  //seg1-E
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 0;  //seg1-F
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 0;  //seg1-H
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 0;  //seg1-J
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 0;  //seg1-K
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 0;  //seg1-G2
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 0;  //seg1-L
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 0;  //seg1-M
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 0;  //seg1-N
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 0;  //seg1-G1
       PORTB.1 = 1;
       PORTB.1 = 0;
      }
      
void num8()
      {
       PORTB.0 = 1;  //seg1-A1
       PORTB.1 = 1;
       PORTB.1 = 0;   
       PORTB.0 = 1;  //seg1-A2
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 1;  //seg1-B
       PORTB.1 = 1;
       PORTB.1 = 0;  
       PORTB.0 = 1;  //seg1-C
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 1;  //seg1-D2
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 1;  //seg1-D1
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 1;  //seg1-E
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 1;  //seg1-F
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 0;  //seg1-H
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 0;  //seg1-J
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 0;  //seg1-K
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 1;  //seg1-G2
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 0;  //seg1-L
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 0;  //seg1-M
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 0;  //seg1-N
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 1;  //seg1-G1
       PORTB.1 = 1;
       PORTB.1 = 0;
      }
      
void num9()
      {
       PORTB.0 = 1;  //seg1-A1
       PORTB.1 = 1;
       PORTB.1 = 0;   
       PORTB.0 = 1;  //seg1-A2
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 1;  //seg1-B
       PORTB.1 = 1;
       PORTB.1 = 0;  
       PORTB.0 = 1;  //seg1-C
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 1;  //seg1-D2
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 1;  //seg1-D1
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 0;  //seg1-E
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 1;  //seg1-F
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 0;  //seg1-H
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 0;  //seg1-J
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 0;  //seg1-K
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 1;  //seg1-G2
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 0;  //seg1-L
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 0;  //seg1-M
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 0;  //seg1-N
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 1;  //seg1-G1
       PORTB.1 = 1;
       PORTB.1 = 0;
      }

#endif