#ifndef _ALPHABET_INCLUDED_
#define _ALPHABET_INCLUDED_

void alphabetA()
      {
       PORTB.0 = 1;  //seg1-A1
       PORTB.1 = 1;
       PORTB.1 = 0;   
       PORTB.0 = 1;  //seg1-A2
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 1;  //seg1-B
       PORTB.1 = 1;
       PORTB.1 = 0;  
       PORTB.0 = 1;  //seg1-C
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 0;  //seg1-D2
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 0;  //seg1-D1
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 1;  //seg1-E
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 1;  //seg1-F
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 0;  //seg1-H
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 0;  //seg1-J
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 0;  //seg1-K
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 1;  //seg1-G2
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 0;  //seg1-L
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 0;  //seg1-M
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 0;  //seg1-N
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 1;  //seg1-G1
       PORTB.1 = 1;
       PORTB.1 = 0;
      }         
      
void alphabetB()
      {
       PORTB.0 = 1;  //seg1-A1
       PORTB.1 = 1;
       PORTB.1 = 0;   
       PORTB.0 = 1;  //seg1-A2
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 1;  //seg1-B
       PORTB.1 = 1;
       PORTB.1 = 0;  
       PORTB.0 = 1;  //seg1-C
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 1;  //seg1-D2
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 1;  //seg1-D1
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 0;  //seg1-E
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 0;  //seg1-F
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 0;  //seg1-H
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 1;  //seg1-J
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 0;  //seg1-K
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 1;  //seg1-G2
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 0;  //seg1-L
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 1;  //seg1-M
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 0;  //seg1-N
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 0;  //seg1-G1
       PORTB.1 = 1;
       PORTB.1 = 0;
      }

void alphabetC()
      {
       PORTB.0 = 1;  //seg1-A1
       PORTB.1 = 1;
       PORTB.1 = 0;   
       PORTB.0 = 1;  //seg1-A2
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 0;  //seg1-B
       PORTB.1 = 1;
       PORTB.1 = 0;  
       PORTB.0 = 0;  //seg1-C
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 1;  //seg1-D2
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 1;  //seg1-D1
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 1;  //seg1-E
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 1;  //seg1-F
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 0;  //seg1-H
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 0;  //seg1-J
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 0;  //seg1-K
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 0;  //seg1-G2
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 0;  //seg1-L
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 0;  //seg1-M
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 0;  //seg1-N
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 0;  //seg1-G1
       PORTB.1 = 1;
       PORTB.1 = 0;
      }  
              
void alphabetD()
      {
       PORTB.0 = 1;  //seg1-A1
       PORTB.1 = 1;
       PORTB.1 = 0;   
       PORTB.0 = 1;  //seg1-A2
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 1;  //seg1-B
       PORTB.1 = 1;
       PORTB.1 = 0;  
       PORTB.0 = 1;  //seg1-C
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 1;  //seg1-D2
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 1;  //seg1-D1
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 0;  //seg1-E
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 0;  //seg1-F
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 0;  //seg1-H
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 1;  //seg1-J
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 0;  //seg1-K
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 0;  //seg1-G2
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 0;  //seg1-L
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 1;  //seg1-M
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 0;  //seg1-N
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 0;  //seg1-G1
       PORTB.1 = 1;
       PORTB.1 = 0;
      }
      
void alphabetE()
      {
       PORTB.0 = 1;  //seg1-A1
       PORTB.1 = 1;
       PORTB.1 = 0;   
       PORTB.0 = 1;  //seg1-A2
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 0;  //seg1-B
       PORTB.1 = 1;
       PORTB.1 = 0;  
       PORTB.0 = 0;  //seg1-C
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 1;  //seg1-D2
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 1;  //seg1-D1
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 1;  //seg1-E
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 1;  //seg1-F
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 0;  //seg1-H
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 0;  //seg1-J
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 0;  //seg1-K
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 0;  //seg1-G2
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 0;  //seg1-L
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 0;  //seg1-M
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 0;  //seg1-N
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 1;  //seg1-G1
       PORTB.1 = 1;
       PORTB.1 = 0;
      } 
        
void alphabetF()
      {
       PORTB.0 = 1;  //seg1-A1
       PORTB.1 = 1;
       PORTB.1 = 0;   
       PORTB.0 = 1;  //seg1-A2
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 0;  //seg1-B
       PORTB.1 = 1;
       PORTB.1 = 0;  
       PORTB.0 = 0;  //seg1-C
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 0;  //seg1-D2
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 0;  //seg1-D1
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 1;  //seg1-E
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 1;  //seg1-F
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 0;  //seg1-H
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 0;  //seg1-J
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 0;  //seg1-K
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 0;  //seg1-G2
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 0;  //seg1-L
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 0;  //seg1-M
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 0;  //seg1-N
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 1;  //seg1-G1
       PORTB.1 = 1;
       PORTB.1 = 0;
      } 
      
      
void alphabetG()
      {
       PORTB.0 = 1;  //seg1-A1
       PORTB.1 = 1;
       PORTB.1 = 0;   
       PORTB.0 = 1;  //seg1-A2
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 0;  //seg1-B
       PORTB.1 = 1;
       PORTB.1 = 0;  
       PORTB.0 = 1;  //seg1-C
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 1;  //seg1-D2
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 1;  //seg1-D1
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 1;  //seg1-E
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 1;  //seg1-F
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 0;  //seg1-H
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 0;  //seg1-J
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 0;  //seg1-K
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 1;  //seg1-G2
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 0;  //seg1-L
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 0;  //seg1-M
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 0;  //seg1-N
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 0;  //seg1-G1
       PORTB.1 = 1;
       PORTB.1 = 0;
      }           
      
void alphabetH()
      {
       PORTB.0 = 0;  //seg1-A1
       PORTB.1 = 1;
       PORTB.1 = 0;   
       PORTB.0 = 0;  //seg1-A2
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 1;  //seg1-B
       PORTB.1 = 1;
       PORTB.1 = 0;  
       PORTB.0 = 1;  //seg1-C
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 0;  //seg1-D2
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 0;  //seg1-D1
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 1;  //seg1-E
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 1;  //seg1-F
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 0;  //seg1-H
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 0;  //seg1-J
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 0;  //seg1-K
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 1;  //seg1-G2
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 0;  //seg1-L
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 0;  //seg1-M
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 0;  //seg1-N
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 1;  //seg1-G1
       PORTB.1 = 1;
       PORTB.1 = 0;
      }    
      
void alphabetI()
      {
       PORTB.0 = 1;  //seg1-A1
       PORTB.1 = 1;
       PORTB.1 = 0;   
       PORTB.0 = 1;  //seg1-A2
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 0;  //seg1-B
       PORTB.1 = 1;
       PORTB.1 = 0;  
       PORTB.0 = 0;  //seg1-C
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 1;  //seg1-D2
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 1;  //seg1-D1
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 0;  //seg1-E
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 0;  //seg1-F
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 0;  //seg1-H
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 1;  //seg1-J
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 0;  //seg1-K
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 0;  //seg1-G2
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 0;  //seg1-L
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 1;  //seg1-M
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 0;  //seg1-N
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 0;  //seg1-G1
       PORTB.1 = 1;
       PORTB.1 = 0;
      }
           
void alphabetJ()
      {
       PORTB.0 = 0;  //seg1-A1
       PORTB.1 = 1;
       PORTB.1 = 0;   
       PORTB.0 = 0;  //seg1-A2
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 1;  //seg1-B
       PORTB.1 = 1;
       PORTB.1 = 0;  
       PORTB.0 = 1;  //seg1-C
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 1;  //seg1-D2
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 1;  //seg1-D1
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 1;  //seg1-E
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 0;  //seg1-F
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 0;  //seg1-H
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 0;  //seg1-J
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 0;  //seg1-K
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 0;  //seg1-G2
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 0;  //seg1-L
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 0;  //seg1-M
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 0;  //seg1-N
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 0;  //seg1-G1
       PORTB.1 = 1;
       PORTB.1 = 0;
      }           
            
void alphabetK()
 {
       PORTB.0 = 0;  //seg1-A1
       PORTB.1 = 1;
       PORTB.1 = 0;   
       PORTB.0 = 0;  //seg1-A2
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 0;  //seg1-B
       PORTB.1 = 1;
       PORTB.1 = 0;  
       PORTB.0 = 0;  //seg1-C
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 0;  //seg1-D2
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 0;  //seg1-D1
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 1;  //seg1-E
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 1;  //seg1-F
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 0;  //seg1-H
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 0;  //seg1-J
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 1;  //seg1-K
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 0;  //seg1-G2
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 1;  //seg1-L
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 0;  //seg1-M
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 0;  //seg1-N
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 1;  //seg1-G1
       PORTB.1 = 1;
       PORTB.1 = 0;
      }    
         
 
 void alphabetL()
 {
       PORTB.0 = 0;  //seg1-A1
       PORTB.1 = 1;
       PORTB.1 = 0;   
       PORTB.0 = 0;  //seg1-A2
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 0;  //seg1-B
       PORTB.1 = 1;
       PORTB.1 = 0;  
       PORTB.0 = 0;  //seg1-C
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 1;  //seg1-D2
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 1;  //seg1-D1
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 1;  //seg1-E
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 1;  //seg1-F
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 0;  //seg1-H
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 0;  //seg1-J
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 0;  //seg1-K
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 0;  //seg1-G2
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 0;  //seg1-L
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 0;  //seg1-M
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 0;  //seg1-N
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 0;  //seg1-G1
       PORTB.1 = 1;
       PORTB.1 = 0;
      } 
      
    
 void alphabetM()
 {
       PORTB.0 = 0;  //seg1-A1
       PORTB.1 = 1;
       PORTB.1 = 0;   
       PORTB.0 = 0;  //seg1-A2
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 1;  //seg1-B
       PORTB.1 = 1;
       PORTB.1 = 0;  
       PORTB.0 = 1;  //seg1-C
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 0;  //seg1-D2
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 0;  //seg1-D1
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 1;  //seg1-E
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 1;  //seg1-F
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 1;  //seg1-H
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 0;  //seg1-J
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 1;  //seg1-K
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 0;  //seg1-G2
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 0;  //seg1-L
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 0;  //seg1-M
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 0;  //seg1-N
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 0;  //seg1-G1
       PORTB.1 = 1;
       PORTB.1 = 0;
      }           
      
 
 void alphabetN()
 {
       PORTB.0 = 0;  //seg1-A1
       PORTB.1 = 1;
       PORTB.1 = 0;   
       PORTB.0 = 0;  //seg1-A2
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 1;  //seg1-B
       PORTB.1 = 1;
       PORTB.1 = 0;  
       PORTB.0 = 1;  //seg1-C
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 0;  //seg1-D2
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 0;  //seg1-D1
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 1;  //seg1-E
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 1;  //seg1-F
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 1;  //seg1-H
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 0;  //seg1-J
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 0;  //seg1-K
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 0;  //seg1-G2
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 1;  //seg1-L
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 0;  //seg1-M
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 0;  //seg1-N
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 0;  //seg1-G1
       PORTB.1 = 1;
       PORTB.1 = 0;
      }       
         
      
 void alphabetO()
 {
       PORTB.0 = 1;  //seg1-A1
       PORTB.1 = 1;
       PORTB.1 = 0;   
       PORTB.0 = 1;  //seg1-A2
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 1;  //seg1-B
       PORTB.1 = 1;
       PORTB.1 = 0;  
       PORTB.0 = 1;  //seg1-C
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 1;  //seg1-D2
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 1;  //seg1-D1
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 1;  //seg1-E
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 1;  //seg1-F
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 0;  //seg1-H
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 0;  //seg1-J
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 0;  //seg1-K
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 0;  //seg1-G2
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 0;  //seg1-L
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 0;  //seg1-M
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 0;  //seg1-N
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 0;  //seg1-G1
       PORTB.1 = 1;
       PORTB.1 = 0;
      }           
      
      
 void alphabetP()
    {
       PORTB.0 = 1;  //seg1-A1
       PORTB.1 = 1;
       PORTB.1 = 0;   
       PORTB.0 = 1;  //seg1-A2
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 1;  //seg1-B
       PORTB.1 = 1;
       PORTB.1 = 0;  
       PORTB.0 = 0;  //seg1-C
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 0;  //seg1-D2
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 0;  //seg1-D1
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 1;  //seg1-E
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 1;  //seg1-F
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 0;  //seg1-H
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 0;  //seg1-J
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 0;  //seg1-K
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 1;  //seg1-G2
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 0;  //seg1-L
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 0;  //seg1-M
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 0;  //seg1-N
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 1;  //seg1-G1
       PORTB.1 = 1;
       PORTB.1 = 0;
      }           
      
 void alphabetQ()
 {
       PORTB.0 = 1;  //seg1-A1
       PORTB.1 = 1;
       PORTB.1 = 0;   
       PORTB.0 = 1;  //seg1-A2
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 1;  //seg1-B
       PORTB.1 = 1;
       PORTB.1 = 0;  
       PORTB.0 = 1;  //seg1-C
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 1;  //seg1-D2
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 1;  //seg1-D1
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 1;  //seg1-E
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 1;  //seg1-F
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 0;  //seg1-H
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 0;  //seg1-J
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 0;  //seg1-K
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 0;  //seg1-G2
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 1;  //seg1-L
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 0;  //seg1-M
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 0;  //seg1-N
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 0;  //seg1-G1
       PORTB.1 = 1;
       PORTB.1 = 0;
      }           
      
 
 void alphabetR()
 {
       PORTB.0 = 1;  //seg1-A1
       PORTB.1 = 1;
       PORTB.1 = 0;   
       PORTB.0 = 1;  //seg1-A2
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 1;  //seg1-B
       PORTB.1 = 1;
       PORTB.1 = 0;  
       PORTB.0 = 0;  //seg1-C
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 0;  //seg1-D2
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 0;  //seg1-D1
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 1;  //seg1-E
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 1;  //seg1-F
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 0;  //seg1-H
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 0;  //seg1-J
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 0;  //seg1-K
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 1;  //seg1-G2
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 1;  //seg1-L
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 0;  //seg1-M
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 0;  //seg1-N
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 1;  //seg1-G1
       PORTB.1 = 1;
       PORTB.1 = 0;
      } 
      
 
 void alphabetS()
 {
       PORTB.0 = 1;  //seg1-A1
       PORTB.1 = 1;
       PORTB.1 = 0;   
       PORTB.0 = 1;  //seg1-A2
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 0;  //seg1-B
       PORTB.1 = 1;
       PORTB.1 = 0;  
       PORTB.0 = 1;  //seg1-C
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 1;  //seg1-D2
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 1;  //seg1-D1
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 0;  //seg1-E
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 1;  //seg1-F
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 0;  //seg1-H
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 0;  //seg1-J
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 0;  //seg1-K
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 1;  //seg1-G2
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 0;  //seg1-L
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 0;  //seg1-M
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 0;  //seg1-N
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 1;  //seg1-G1
       PORTB.1 = 1;
       PORTB.1 = 0;
      }           
      
 void alphabetT()
 {
       PORTB.0 = 1;  //seg1-A1
       PORTB.1 = 1;
       PORTB.1 = 0;   
       PORTB.0 = 1;  //seg1-A2
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 0;  //seg1-B
       PORTB.1 = 1;
       PORTB.1 = 0;  
       PORTB.0 = 0;  //seg1-C
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 0;  //seg1-D2
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 0;  //seg1-D1
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 0;  //seg1-E
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 0;  //seg1-F
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 0;  //seg1-H
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 1;  //seg1-J
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 0;  //seg1-K
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 0;  //seg1-G2
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 0;  //seg1-L
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 1;  //seg1-M
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 0;  //seg1-N
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 0;  //seg1-G1
       PORTB.1 = 1;
       PORTB.1 = 0;
      }           
      
 void alphabetU()
 {
       PORTB.0 = 0;  //seg1-A1
       PORTB.1 = 1;
       PORTB.1 = 0;   
       PORTB.0 = 0;  //seg1-A2
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 1;  //seg1-B
       PORTB.1 = 1;
       PORTB.1 = 0;  
       PORTB.0 = 1;  //seg1-C
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 1;  //seg1-D2
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 1;  //seg1-D1
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 1;  //seg1-E
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 1;  //seg1-F
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 0;  //seg1-H
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 0;  //seg1-J
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 0;  //seg1-K
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 0;  //seg1-G2
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 0;  //seg1-L
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 0;  //seg1-M
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 0;  //seg1-N
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 0;  //seg1-G1
       PORTB.1 = 1;
       PORTB.1 = 0;
      } 
      
 void alphabetV()
 {
       PORTB.0 = 0;  //seg1-A1
       PORTB.1 = 1;
       PORTB.1 = 0;   
       PORTB.0 = 0;  //seg1-A2
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 0;  //seg1-B
       PORTB.1 = 1;
       PORTB.1 = 0;  
       PORTB.0 = 0;  //seg1-C
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 0;  //seg1-D2
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 0;  //seg1-D1
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 1;  //seg1-E
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 1;  //seg1-F
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 0;  //seg1-H
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 0;  //seg1-J
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 1;  //seg1-K
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 0;  //seg1-G2
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 0;  //seg1-L
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 0;  //seg1-M
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 1;  //seg1-N
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 0;  //seg1-G1
       PORTB.1 = 1;
       PORTB.1 = 0;
      } 
                  
      
 void alphabetW()
 {
       PORTB.0 = 0;  //seg1-A1
       PORTB.1 = 1;
       PORTB.1 = 0;   
       PORTB.0 = 0;  //seg1-A2
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 1;  //seg1-B
       PORTB.1 = 1;
       PORTB.1 = 0;  
       PORTB.0 = 1;  //seg1-C
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 0;  //seg1-D2
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 0;  //seg1-D1
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 1;  //seg1-E
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 1;  //seg1-F
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 0;  //seg1-H
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 0;  //seg1-J
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 0;  //seg1-K
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 0;  //seg1-G2
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 1;  //seg1-L
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 0;  //seg1-M
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 1;  //seg1-N
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 0;  //seg1-G1
       PORTB.1 = 1;
       PORTB.1 = 0;
      }           
      
 void alphabetX()
 {
       PORTB.0 = 0;  //seg1-A1
       PORTB.1 = 1;
       PORTB.1 = 0;   
       PORTB.0 = 0;  //seg1-A2
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 0;  //seg1-B
       PORTB.1 = 1;
       PORTB.1 = 0;  
       PORTB.0 = 0;  //seg1-C
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 0;  //seg1-D2
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 0;  //seg1-D1
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 0;  //seg1-E
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 0;  //seg1-F
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 1;  //seg1-H
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 0;  //seg1-J
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 1;  //seg1-K
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 0;  //seg1-G2
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 1;  //seg1-L
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 0;  //seg1-M
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 1;  //seg1-N
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 0;  //seg1-G1
       PORTB.1 = 1;
       PORTB.1 = 0;
      }           
      
      
 void alphabetY()
 {
       PORTB.0 = 0;  //seg1-A1
       PORTB.1 = 1;
       PORTB.1 = 0;   
       PORTB.0 = 0;  //seg1-A2
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 1;  //seg1-B
       PORTB.1 = 1;
       PORTB.1 = 0;  
       PORTB.0 = 1;  //seg1-C
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 1;  //seg1-D2
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 1;  //seg1-D1
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 0;  //seg1-E
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 1;  //seg1-F
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 0;  //seg1-H
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 0;  //seg1-J
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 0;  //seg1-K
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 1;  //seg1-G2
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 0;  //seg1-L
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 0;  //seg1-M
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 0;  //seg1-N
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 1;  //seg1-G1
       PORTB.1 = 1;
       PORTB.1 = 0;
      }   
      
 void alphabetZ()
 {
       PORTB.0 = 1;  //seg1-A1
       PORTB.1 = 1;
       PORTB.1 = 0;   
       PORTB.0 = 1;  //seg1-A2
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 0;  //seg1-B
       PORTB.1 = 1;
       PORTB.1 = 0;  
       PORTB.0 = 0;  //seg1-C
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 1;  //seg1-D2
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 1;  //seg1-D1
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 0;  //seg1-E
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 0;  //seg1-F
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 0;  //seg1-H
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 0;  //seg1-J
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 1;  //seg1-K
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 0;  //seg1-G2
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 0;  //seg1-L
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 0;  //seg1-M
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 1;  //seg1-N
       PORTB.1 = 1;
       PORTB.1 = 0;
       PORTB.0 = 0;  //seg1-G1
       PORTB.1 = 1;
       PORTB.1 = 0;
      } 
#endif